### ISSUE TITLE
DatabaseInitialized hook not being called

### ISSUE THREAD

**Issue by fruitwasp** [FPtje/MySQLite#7]
The removal of the timer around the ```connectToMySQL``` call caused the ```DatabaseInitialized``` hook not being called somehow. Reverting the commit made it work again. Using tmysql4.

The commit that broke it: https://github.com/FPtje/MySQLite/commit/a9c798d65c1bdcb09fa7ece2ca564486ea15c693

**Comment by FPtje** [comment]
![hl2_2016-02-20_19-18-48](https://cloud.githubusercontent.com/assets/1202014/13198354/d0ad8ae0-d806-11e5-8718-c7c6d120e2b4.png)

I'm gonna go on a limb and say that you're adding the hook in some kind of timer or InitPostEntity or w/e. It works for me. 

Also, *oh no* the username and password of my local database are in that screenshot.

**Comment by Bo98** [comment]
Looks like it could happen if they hook into it in a DarkRPModification module.

**Comment by FPtje** [comment]
depending on whether darkrpmod modules use the MySQL module on the top level, that commit might break shit. So I'm not merging it with MySQLite yet to test.

**Comment by Skyborder** [comment]
i have dont access edit the FPP Settings ?! LOOL

**Comment by FPtje** [comment]
The fuck are you on about

**Comment by Skyborder** [comment]
Wow nice Reaction man
Idiot

**Comment by Skyborder** [comment]
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] Leon Winter ist nun Zivilist!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
No access!
No access!
No access!
Kristian Sugo (STEAM_0:0:39868904) Spawned a models/props_junk/cardboard_box002a.mdl
Kristian Sugo<STEAM_0:0:39868904> spawned model models/props_junk/cardboard_box002a.mdl
[DarkRP] Zahltag! Du hast €244 erhalten! (25% Steuern)
Kristian Sugo (STEAM_0:0:39868904) Spawned a models/props_phx/construct/metal_plate2x2.mdl
Kristian Sugo<STEAM_0:0:39868904> spawned model models/props_phx/construct/metal_plate2x2.mdl
Rufe einen Notartz mit /911 Grund
FuchsIsBack Twitch earned the achievement Bad Coder
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
VehicleType:prop_vehicle_jeep:
[DarkRP] Zahltag! Du hast €244 erhalten! (25% Steuern)

**Comment by Skyborder** [comment]
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] Leon Winter ist nun Zivilist!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
No access!
No access!
No access!

Rufe einen Notartz mit /911 Grund
FuchsIsBack Twitch earned the achievement Bad Coder
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
[DarkRP] There is 1 Lua problem!
Please check your console for more information!
VehicleType:prop_vehicle_jeep:
[DarkRP] Zahltag! Du hast €244 erhalten! (25% Steuern)

**Comment by Bo98** [comment]
Scroll up and give us the actual Lua error instead of just the "There is 1 Lua problem" part. It begins with "[ERROR]" and is several lines long

**Comment by Skyborder** [comment]
I cant set the Settings Menü
Client Write No Access and i am have Superadmin

**Comment by Skyborder** [comment]
is Dont works
The Error is Clear

And the Settup can i not use

**Comment by FPtje** [comment]
Not a help forum. Get out.

**Comment by Skyborder** [comment]
Sry i can dont Get Out
I have 22 Ranks on my Server and one Ranks have never access this is from your fucking Update yesterday or today

**Comment by fruitwasp** [comment]
Head over to http://forum.darkrp.com/ and post your issue there.

**Comment by FPtje** [comment]
Give the actual error.

**Comment by Skyborder** [comment]
No i have Found FPtje
I have Update ULX & ULIB and DarkRP
what is my Fail for your ULX Update is all Works :(

**Comment by Skyborder** [comment]
[ERROR] addons/ulx/lua/ulx/modules/sh/user.lua:57: Group does not exist for adding user to (superadmin)

**Comment by Skyborder** [comment]
Ok i write God to Serveradmin Privileges
And No Access here a Pic
http://picload.org/image/wcggpla/fpp.png

**Comment by Skyborder** [comment]
Ok your ULX Version is this not
this is FPP

**Comment by Skyborder** [comment]
and i have no errors or so
I become the right not for superadmin

**Comment by Skyborder** [comment]
FPtje:

**Comment by FPtje** [comment]
Dealt with.

**Comment by fruitwasp** [comment]
Your fix resolved the problem I had.

**Comment by HDG-MrDeeJay** [comment]
I like how skyborder called you an idiot for asking him to explain what he said in his chopped up english.
